parameters:
  - name: environment
    type: string
  - name: serviceName
    type: string
  - name: deployPath
    type: string
  - name: variableGroup
    type: string
  - name: dependsOn
    type: string

stages:
  - stage: Deploy${{ parameters.environment }}
    displayName: Deploy to ${{ parameters.environment }}
    dependsOn: ${{ parameters.dependsOn }}
    variables:
      - group: ${{ parameters.variableGroup }}
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - checkout: none

          - task: PowerShell@2
            displayName: 'Stop Service'
            inputs:
              targetType: 'inline'
              script: |
                $ErrorActionPreference = "Continue"
                $serviceName = "${{ parameters.serviceName }}"
                $timeout = 60

                $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
                if (-not $service) {
                    Write-Host "Service does not exist"
                    exit 0
                }

                Write-Host "Current service status: $($service.Status)"

                if ($service.Status -eq "Stopped") {
                    Write-Host "Service is already stopped"
                    exit 0
                }

                Write-Host "Stopping service: $serviceName"
                Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue

                $elapsed = 0
                while ($elapsed -lt $timeout) {
                    Start-Sleep -Seconds 2
                    $elapsed += 2

                    $service.Refresh()
                    Write-Host "Service status: $($service.Status)"

                    if ($service.Status -eq "Stopped") {
                        Write-Host "Service stopped successfully"
                        exit 0
                    }
                }

                Write-Host "Service did not stop gracefully, forcing termination..."
                $process = Get-Process -Name "UKSF.Api" -ErrorAction SilentlyContinue
                if ($process) {
                    Write-Host "Killing process (PID: $($process.Id))"
                    Stop-Process -Id $process.Id -Force
                    Start-Sleep -Seconds 5
                }

                Write-Host "Service stop complete"

          - task: CopyFiles@2
            displayName: 'Copy Files'
            inputs:
              SourceFolder: '$(buildOutput)'
              Contents: '**'
              TargetFolder: '${{ parameters.deployPath }}'
              CleanTargetFolder: true
              OverWrite: true

          - task: FileTransform@2
            displayName: 'Transform appsettings'
            inputs:
              folderPath: '${{ parameters.deployPath }}'
              xmlTransformationRules: ''
              jsonTargetFiles: 'appsettings.json'

          - task: PowerShell@2
            displayName: 'Start Service'
            inputs:
              targetType: 'inline'
              script: |
                $ErrorActionPreference = "Continue"
                $serviceName = "${{ parameters.serviceName }}"
                $timeout = 30

                $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
                if (-not $service) {
                    Write-Error "Service does not exist"
                    exit 1
                }

                Write-Host "Current service status: $($service.Status)"

                if ($service.Status -eq "Running") {
                    Write-Host "Service is already running"
                    exit 0
                }

                Write-Host "Starting service: $serviceName"
                Start-Service -Name $serviceName

                $elapsed = 0
                while ($elapsed -lt $timeout) {
                    Start-Sleep -Seconds 2
                    $elapsed += 2

                    $service.Refresh()
                    Write-Host "Service status: $($service.Status)"

                    if ($service.Status -eq "Running") {
                        Write-Host "Service started successfully"
                        exit 0
                    }
                }

                Write-Error "Service failed to start within $timeout seconds"
                exit 1
