name: Build & Run Tests
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with dotnet
      run: dotnet build -c Release
    - name: Run tests with coverage
      run: dotnet test ./UKSF.Api.sln -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info /p:Exclude="[UKSF.PostMessage]*"
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
